defmodule LangExtract.ChunkerParityTest do
  @moduledoc """
  Differential tests against upstream langextract's ChunkIterator.

  Fixtures are generated by benchmark/scripts/gen_chunker_fixtures.py,
  which runs each (text, max_char_buffer) case through the upstream
  chunker and freezes every chunk's text and byte offsets. Upstream
  behavior is the executable spec: chunk boundaries must land identically
  across the two libraries — the cross-library benchmarks depend on that.

  Upstream chunks are token intervals: chunk text spans the first token's
  start to the last token's end, so whitespace between chunks belongs to
  no chunk and chunks do not tile the source.
  """
  use ExUnit.Case, async: true

  alias LangExtract.Chunker
  alias LangExtract.Test.ChunkerBaseline

  # Both implementations answer to upstream's verdicts on every run: the
  # production chunker and the frozen line-comparable baseline.
  @implementations [production: Chunker, baseline: ChunkerBaseline]

  @fixtures "test/fixtures/chunker_parity.json"
            |> File.read!()
            |> Jason.decode!()

  for {label, chunker} <- @implementations, fixture <- @fixtures do
    @chunker chunker
    @fixture fixture

    test "#{label} matches upstream on #{fixture["name"]}" do
      %{"text" => text, "max_char_buffer" => max_chars, "chunks" => expected} = @fixture

      chunks =
        text
        |> @chunker.chunk(max_chunk_chars: max_chars)
        |> Enum.map(
          &%{"text" => &1.text, "byte_start" => &1.byte_start, "byte_end" => &1.byte_end}
        )

      assert chunks == expected
    end
  end
end
