defmodule LangExtract.Alignment.AlignerParityTest do
  @moduledoc """
  Differential tests against upstream langextract's WordAligner.

  Fixtures are generated by benchmark/scripts/gen_alignment_fixtures.py,
  which runs each case — a source text plus a LIST of extractions in model
  output order — through the upstream aligner (v1.6.0 + #485) and freezes
  its statuses and byte spans. Upstream behavior is the executable spec;
  any case where we intentionally differ must be listed in the divergence
  ledger below with its reason.
  """
  use ExUnit.Case, async: true

  alias LangExtract.Alignment.Aligner
  alias LangExtract.Span

  @fixtures "test/fixtures/alignment_parity.json"
            |> File.read!()
            |> Jason.decode!()

  # Divergence ledger, keyed by {case name, extraction index} and split by
  # severity. One divergence family feeds it: leftover phases are
  # per-extraction here, joint upstream — after the occurrence DP, upstream
  # reruns difflib over the concatenated tokens of ALL sibling extractions,
  # so siblings change block decomposition for the leftovers. We run each
  # leftover through the standalone phases instead; DP claims mask only the
  # lesser phase (so a paraphrase of an already-claimed repeat is
  # :not_found on both sides — no entry needed).
  #
  # Label divergences ground exactly upstream's bytes under a different
  # status — favorable (we say :exact where upstream degrades to fuzzy);
  # a table comment suffices to add one.
  @label_divergences %{
    {"dp_out_of_order_emission", 0} => %{status: :exact, byte_start: 10, byte_end: 13},
    {"dp_contested_overlap", 1} => %{status: :exact, byte_start: 4, byte_end: 11},
    {"dp_nested_inside_placement", 1} => %{status: :exact, byte_start: 10, byte_end: 15},
    {"dp_nested_mention_punctuated", 1} => %{status: :exact, byte_start: 19, byte_end: 27}
  }

  # Existence divergences drop or invent a grounded span relative to
  # upstream. They are lossy: adding one requires an entry in CLAUDE.md's
  # decision log stating the trade, not just a line here. Empty today —
  # keep it that way absent a strong reason (see the 32599f3 lesson in the
  # decision log).
  @existence_divergences %{}

  @known_divergences Map.merge(@label_divergences, @existence_divergences)

  # Fixture config keys map onto align/3 options; unknown keys fail loudly.
  config_keys = %{
    "fuzzy_threshold" => :fuzzy_threshold,
    "min_density" => :min_density,
    "accept_lesser" => :accept_lesser
  }

  for fixture <- @fixtures do
    @fixture fixture

    # Computed at module level: inside the test the unrolled fixture literal
    # gives 1.20's type checker a heterogeneous union it can't enumerate.
    @opts fixture
          |> Map.get("config", %{})
          |> Enum.map(fn {key, value} -> {Map.fetch!(config_keys, key), value} end)

    test "matches upstream on #{fixture["name"]}" do
      %{"source" => source, "extractions" => extractions, "results" => results} = @fixture

      spans = Aligner.align(source, extractions, @opts)
      # Enum.count, not length: 1.20's type checker can't see through the
      # heterogeneous fixture-map literal and unions its value types.
      assert length(spans) == Enum.count(results)

      for {{%Span{} = span, expected}, idx} <- Enum.with_index(Enum.zip(spans, results)) do
        expected =
          Map.get(@known_divergences, {@fixture["name"], idx}) ||
            %{
              status: String.to_existing_atom(expected["status"]),
              byte_start: expected["byte_start"],
              byte_end: expected["byte_end"]
            }

        assert span.status == expected.status,
               "extraction #{idx}: status #{span.status}, expected #{expected.status}"

        assert span.byte_start == expected.byte_start, "extraction #{idx}: byte_start"
        assert span.byte_end == expected.byte_end, "extraction #{idx}: byte_end"
      end
    end
  end
end
