defmodule LangExtract.Alignment.AlignerParityTest do
  @moduledoc """
  Differential tests against upstream langextract's WordAligner.

  Fixtures are generated by benchmark/scripts/gen_alignment_fixtures.py,
  which runs each case — a source text plus a LIST of extractions in model
  output order — through the upstream aligner (v1.6.0 + #485) and freezes
  its statuses and byte spans. Upstream behavior is the executable spec;
  any case where we intentionally differ must be listed in
  @known_divergences with its reason.
  """
  use ExUnit.Case, async: true

  alias LangExtract.Alignment.Aligner
  alias LangExtract.Span

  @fixtures "test/fixtures/alignment_parity.json"
            |> File.read!()
            |> Jason.decode!()

  # Keyed by {case name, extraction index}. One divergence family:
  # (the contraction-tokenization family closed when the tokenizer adopted
  # upstream's letter/digit/symbol-run splitting — smart_quote_contraction
  # now asserts the fixture's real upstream result.)
  #
  # Leftover phases are per-extraction here, joint upstream: after the
  # occurrence DP, upstream reruns difflib over the concatenated tokens of
  # ALL sibling extractions, so siblings change block decomposition for the
  # leftovers. We run each leftover through the standalone phases instead.
  # Consequences: out-of-order or contested leftovers ground as :exact where
  # upstream degrades to fuzzy at the same bytes (favorable), and a
  # paraphrase of an already-claimed repeat grounds its prefix where
  # upstream returns not_found (documented trade-off).
  @known_divergences %{
    {"dp_out_of_order_emission", 0} => %{status: :exact, byte_start: 10, byte_end: 13},
    {"dp_contested_overlap", 1} => %{status: :exact, byte_start: 4, byte_end: 11},
    {"dp_paraphrase_among_repeats", 2} => %{status: :fuzzy, byte_start: 0, byte_end: 8}
  }

  for fixture <- @fixtures do
    @fixture fixture

    test "matches upstream on #{fixture["name"]}" do
      %{"source" => source, "extractions" => extractions, "results" => results} = @fixture

      spans = Aligner.align(source, extractions)
      # Enum.count, not length: 1.20's type checker can't see through the
      # heterogeneous fixture-map literal and unions its value types.
      assert length(spans) == Enum.count(results)

      for {{%Span{} = span, expected}, idx} <- Enum.with_index(Enum.zip(spans, results)) do
        expected =
          Map.get(@known_divergences, {@fixture["name"], idx}) ||
            %{
              status: String.to_existing_atom(expected["status"]),
              byte_start: expected["byte_start"],
              byte_end: expected["byte_end"]
            }

        assert span.status == expected.status,
               "extraction #{idx}: status #{span.status}, expected #{expected.status}"

        assert span.byte_start == expected.byte_start, "extraction #{idx}: byte_start"
        assert span.byte_end == expected.byte_end, "extraction #{idx}: byte_end"
      end
    end
  end
end
