defmodule LangExtract.Alignment.AlignerParityTest do
  @moduledoc """
  Differential tests against upstream langextract's WordAligner.

  Fixtures are generated by benchmark/scripts/gen_alignment_fixtures.py,
  which runs each case through the upstream aligner (v1.6.0) and freezes its
  status and byte span. Upstream behavior is the executable spec; any case
  where we intentionally differ must be listed in @known_divergences with
  its reason.
  """
  use ExUnit.Case, async: true

  alias LangExtract.Alignment.{Aligner, Span}

  @fixtures "test/fixtures/alignment_parity.json"
            |> File.read!()
            |> Jason.decode!()

  # Tokenizers differ by design: we keep contractions whole ("don't" is one
  # token); upstream splits them (don / ' / t), letting its lesser phase
  # ground the "don" fragment. Documented 0.1.0 divergence.
  @known_divergences %{
    "smart_quote_contraction" => :not_found
  }

  for fixture <- @fixtures do
    @fixture fixture

    test "matches upstream on #{fixture["name"]}" do
      %{"source" => source, "extraction" => extraction} = @fixture

      [%Span{} = span] = Aligner.align(source, [extraction])

      case Map.fetch(@known_divergences, @fixture["name"]) do
        {:ok, expected_status} ->
          assert span.status == expected_status

        :error ->
          assert span.status == String.to_existing_atom(@fixture["upstream_status"])
          assert span.byte_start == @fixture["upstream_byte_start"]
          assert span.byte_end == @fixture["upstream_byte_end"]
      end
    end
  end
end
